alter table public.products add column if not exists image_url text;
delete from public.order_items; delete from public.products; delete from public.categories;
insert into public.categories (slug,name,sort_order) values
('creatina','Creatina',1),('whey-protein','Whey Protein',2),('barra-de-proteina','Barras de Proteínas',3),('hipercalorico','Hipercalórico',4),('glutamina','Glutamina',5),('pre-treino','Pré treino',6),('vestuario','Vestuário',7),('acessorios','Acessórios',8);
insert into public.products (slug,name,category_id,price_cents,compare_at_cents,image_key,image_url,tags,flavors,reviews_count,is_featured,is_new)
select v.slug, v.name, c.id, v.price, v.cmp, v.ik,
  'https://cdn.shopify.com/s/files/1/0742/9632/8446/files/'||v.img,
  v.tags, v.flav, v.rev, v.feat, v.new
from (values
('creatina-100-pura-300g-integralmedica','Creatina 100% Pura 300g Hardcore','creatina',6000,null,'creatina','creatina-100-pura-300g-hardcore-8615788.png',ARRAY['Sem aditivos','Zero açúcar','Energia muscular']::text[],ARRAY['Sem sabor']::text[],2522,true,false),
('creatina-100-pura-1kg','Creatina 100% Pura Pouch 1kg','creatina',15600,null,'creatina','10610-im-imagens-para-loja-oficial-e-mktplaces-listings-creatinas-1kg-1.png',ARRAY['Sem aditivos','Zero açúcar','Energia muscular']::text[],ARRAY['Sem sabor']::text[],895,true,false),
('creatina-100-pura-120caps','Creatina 100% Pura 120 Cápsulas','creatina',4800,null,'creatina','creatina-100-pura-120-capsulas-9264068.png',ARRAY['Sem aditivos','Zero açúcar','Energia muscular']::text[],ARRAY['Sem sabor']::text[],569,true,false),
('creatina-100-pura-150g-integralmedica','Creatina 100% Pura 150g Hardcore','creatina',3300,null,'creatina','creatina-100-pura-150g-hardcore-5813575.jpg',ARRAY['Sem aditivos','Zero açúcar','Energia muscular']::text[],ARRAY['Sem sabor']::text[],429,true,false),
('creatina-350g-hardcore-com-sabor','Creatina 350g Hardcore Com Sabor','creatina',6000,null,'creatina','creatina-350g-hardcore-com-sabor-2565561.png',ARRAY['Lançamento','Zero Carboidratos','Aumento de força','Zero açúcar']::text[],ARRAY['Sem sabor']::text[],79,true,true),
('creatina-100-pura-60caps','Creatina 100% Pura 60 Cápsulas','creatina',2700,null,'creatina','creatina-100-pura-60-capsulas-2594626.png',ARRAY['Zero açúcar','Sem aditivos','Energia muscular']::text[],ARRAY['Sem sabor']::text[],143,true,false),
('creatina-hardcore-500g-pote','Creatina Hardcore 500g Pote','creatina',8300,null,'creatina','creatina-hardcore-500g-pote-5575800.png',ARRAY['Lançamento','Sem aditivos','Zero açúcar','Energia muscular']::text[],ARRAY['Sem sabor']::text[],26,true,true),
('creatina-hardcore-500g-pouch','Creatina Hardcore 500g Pouch','creatina',6600,7800,'creatina','creatina-hardcore-500g-pouch-9943154.png',ARRAY['Lançamento','Sem aditivos','Zero açúcar','Energia muscular']::text[],ARRAY['Sem sabor']::text[],36,true,true),
('creatina-creapure-300g','Creatina Creapure 300g','creatina',18400,null,'creatina','creatina-creapure-300g-9835611.png',ARRAY['Lançamento']::text[],ARRAY['Sem sabor']::text[],11,false,true),
('whey-protein-concentrado-pouch-900g','Whey Protein Concentrado Pouch 900g','whey-protein',20000,22700,'whey','whey-protein-concentrado-pouch-900g-4093255.png',ARRAY['100% Whey Protein','Ganho de massa','Low Carb']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],107,true,false),
('whey-protein-concentrado-900g','Whey Protein Concentrado Pote 900g','whey-protein',24000,null,'whey','whey-protein-concentrado-pote-900g-3796966.png',ARRAY['100% Whey Protein','Ganho de massa','Low Carb']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],100,true,false),
('whey-protein-concentrado-pouch-1-8kg','Whey Protein Concentrado Pouch 1,8Kg','whey-protein',40400,null,'whey','whey-protein-concentrado-pouch-18kg-5856924.png',ARRAY['100% Whey Protein','Ganho de massa','Low Carb']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],54,false,false),
('my-whey-po-pote','MY WHEY Integralmedica – High quality protein powder 900g','whey-protein',17500,null,'whey','my-whey-integralmedica-high-quality-protein-powder-900g-5821156.png',ARRAY['100% Whey Protein','Baixo em gordura','Aumento de saciedade']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],34,false,false),
('whey-protein-isolado-900g','Whey Protein Isolado 900g','whey-protein',48300,null,'whey','whey-protein-isolado-900g-5033515.png',ARRAY['Zero açúcar adicionado','Zero Glúten','Definição Muscular']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],21,false,false),
('whey-protein-pure-sache','Whey Protein Concentrado Sachê','whey-protein',11300,null,'whey','whey-protein-100-pure-em-sache-4298635.jpg',ARRAY['Lançamento','100% Whey Protein','Ganho de massa','Praticidade']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],3,false,true),
('whey-protein-concentrado-sache-unidade','Whey Protein Concentrado Sachê Unidade','whey-protein',1300,null,'whey','whey-protein-100-pure-em-sache-6569622.jpg',ARRAY['Lançamento','Compre por unidade!','100% Whey Protein']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],2,false,true),
('beef-protein-900g','Beef Protein 900g','whey-protein',21100,null,'whey','beef-protein-900g-4203161.png',ARRAY['Lançamento','Zero Lactose','Zero Glúten','30g de Proteína']::text[],ARRAY['Chocolate','Baunilha','Morango']::text[],27,false,true),
('barra-de-proteina-ovomaltine-integralmedica','Protein Crisp Bar Ovomaltine® 12 und','barra-de-proteina',10500,11900,'barra','protein-crisp-bar-ovomaltine-12-und-6023791.png','{}'::text[],ARRAY['Chocolate','Ovomaltine']::text[],425,true,false),
('crisp-bar','Protein Crisp Bar 12 und - barra de proteína Integralmedica','barra-de-proteina',10500,11900,'barra','168238-1600-auto.png','{}'::text[],ARRAY['Chocolate','Ovomaltine']::text[],50,true,false),
('vo2-protein-bar','VO2 Whey Bar 12 unid','barra-de-proteina',7300,null,'barra','165332-1600-auto.png','{}'::text[],ARRAY['Chocolate','Ovomaltine']::text[],15,false,false),
('protein-crisp-bar-unidade-barra-de-proteina-integralmedica','Protein Crisp Bar Unidade - barra de proteína Integralmedica','barra-de-proteina',1100,null,'barra','protein-crisp-bar-unidade-barra-de-proteina-integralmedica-3446479.png',ARRAY['Compre por unidade!']::text[],ARRAY['Chocolate','Ovomaltine']::text[],12,false,false),
('protein-crisp-bar-ovomaltine-unidade','Protein Crisp Bar Ovomaltine® Unidade','barra-de-proteina',1100,null,'barra','protein-crisp-bar-ovomaltine-unidade-8773590.png',ARRAY['Compre por unidade!']::text[],ARRAY['Chocolate','Ovomaltine']::text[],7,false,false),
('vo2-whey-bar-unidade','VO2 Whey Bar Unidade','barra-de-proteina',700,null,'barra','vo2_chocolate_c9323f91-fde1-4d92-a5b7-cde78fec0436.png',ARRAY['Compre por unidade!']::text[],ARRAY['Chocolate','Ovomaltine']::text[],1,false,false),
('creamass-hipercalorico-com-creatina-3kg','Creamass Hipercalórico Integralmedica 3Kg','hipercalorico',13400,14200,'hipercalorico','creamass-hipercalorico-integralmedica-3kg-3684304.png',ARRAY['Com creatina','Com whey protein','Energia muscular']::text[],ARRAY['Chocolate','Baunilha']::text[],43,true,false),
('nutri-whey-hipercalorico','Nutriwhey Gainer','hipercalorico',12000,null,'hipercalorico','nutriwhey-pouch-6670278.jpg',ARRAY['Lançamento','Ganho de massa','Baixo teor de gordura','Aporte energético']::text[],ARRAY['Chocolate','Baunilha']::text[],2,false,true),
('glutamina-em-po-300g','Glutamina 300g em pó','glutamina',7500,null,'bcaa','glutamina-300g-em-po-4794416.png',ARRAY['Imunidade','Zero Sódio','Antioxidante']::text[],ARRAY['Sem sabor']::text[],288,true,false),
('glutamina-em-po-150g','Glutamina em Pó 150g','glutamina',4200,4700,'bcaa','glutamina-em-po-150g-6777824.png',ARRAY['Imunidade','Zero Sódio','Antioxidante']::text[],ARRAY['Sem sabor']::text[],10,false,false),
('zma-60-capsulas','ZMA Testo Booster','glutamina',4300,null,'bcaa','zma-testo-booster-2199254.png','{}'::text[],ARRAY['Sem sabor']::text[],367,false,false),
('pre-treino-prime-md','Pré-Treino Prime MD 300g','pre-treino',11200,null,'preworkout','pre-treino-prime-md-300g-9642547.png',ARRAY['Lançamento','Dual Caffeine','Mais Energia','Foco']::text[],ARRAY['Frutas Vermelhas','Limão']::text[],14,true,true),
('huger-pre-treino-320g','Huger Pré-Treino 320g','pre-treino',9500,15900,'preworkout','huger-pre-treino-320g-6941324.png',ARRAY['Energia','Vitaminas','Zero açúcar']::text[],ARRAY['Frutas Vermelhas','Limão']::text[],42,true,false),
('beta-alanina-em-po-123g','Beta Alanina em Pó 123g','pre-treino',5400,6500,'preworkout','11337_11353_1300X1300_PRE-TREINOS_Beta_Alanina_Po_123g_1.png',ARRAY['Zero açúcar','Redução da fadiga muscular','Zero Sódio']::text[],ARRAY['Frutas Vermelhas','Limão']::text[],22,false,false),
('regata-masculina-integralmedica','Regata Machão Masculina Integralmedica','vestuario',14200,null,'whey','regata-machao-masculina-integralmedica-1949341.jpg',ARRAY['Lançamento']::text[],ARRAY['P','M','G','GG']::text[],1,false,true),
('camiseta-masculina-champion-mentality','Camiseta Over Champion Mentality Integralmedica','vestuario',21000,null,'whey','camiseta-over-champion-mentality-integralmedica-9860523.jpg',ARRAY['Lançamento']::text[],ARRAY['P','M','G','GG']::text[],1,false,true),
('camiseta-masculina-over-since','Camiseta Over Since 1983 Integralmedica','vestuario',17900,null,'whey','camiseta-over-since-1983-integralmedica-1389932.jpg',ARRAY['Lançamento']::text[],ARRAY['P','M','G','GG']::text[],0,false,true),
('camiseta-masculina-raglan-dry','Camiseta Raglan Dry Integralmedica','vestuario',13700,null,'whey','camiseta-raglan-dry-integralmedica-5764496.jpg',ARRAY['Lançamento']::text[],ARRAY['P','M','G','GG']::text[],0,false,true),
('shorts-feminino-legging-bolso','Shorts Legging Bolso Integralmedica','vestuario',16900,null,'whey','shorts-legging-bolso-integralmedica-5505951.jpg',ARRAY['Lançamento']::text[],ARRAY['P','M','G','GG']::text[],0,false,true),
('galao-2-litros','Galão Body Size 2,2 L','acessorios',2700,null,'whey','164256-1600-auto.webp','{}'::text[],ARRAY['Único']::text[],11,false,false),
('coqueteleira-2-doses-vermelha-tritan','Coqueteleira 2 Doses Vermelha Tritan','acessorios',8700,null,'whey','coqueteleira-2-doses-vermelha-tritan-6723808.png','{}'::text[],ARRAY['Único']::text[],4,false,false),
('squeeze-800ml-vermelha-integral','Squeeze 800 ML Vermelha Integral','acessorios',1900,null,'whey','imagem_2025-08-06_191707039.png','{}'::text[],ARRAY['Único']::text[],2,false,false),
('coqueteleira-1-dose-nacional','Coqueteleira 1 Dose Nacional','acessorios',2000,null,'whey','coqueteleira-1-dose-nacional-1392878.jpg','{}'::text[],ARRAY['Único']::text[],10,false,false),
('porta-capsulas-vermelho','Porta-cápsulas Vermelho','acessorios',2000,null,'whey','porta-capsulas-vermelho-1825359.jpg','{}'::text[],ARRAY['Único']::text[],1,false,false),
('coqueteleira-integralmedica-1-dose-600-ml-transparente','Coqueteleira 1 Dose 600 ML Transparente','acessorios',2700,null,'whey','coqueteleira-1-dose-600-ml-transparente-9098220.png','{}'::text[],ARRAY['Único']::text[],11,false,false),
('bone-aba-curva-treino-tam-unico','Boné Aba Curva Treino Tam Único','acessorios',7990,null,'whey','bone-aba-curva-treino-tam-unico-4964669.png','{}'::text[],ARRAY['Único']::text[],2,false,false)
) as v(slug,name,cat,price,cmp,ik,img,tags,flav,rev,feat,new)
join public.categories c on c.slug = v.cat;